# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Posts', path: 'menu', url: 'writing.html'}
#- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/acrosby'}
#- {icon: 'gitlab', link: 'https://www.gitlab.com/acrosby'}
#- {icon: 'gitlab', link: 'https://www.gitlab.com/bitbucket'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/crosbyar/'}
- {icon: 'rss-square', link: '/feed.xml'}
#- {icon: 'rss-square', link: '/rss-feed.xml'}
#- {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Published on'
